#! /bin/bash
# Turns on viewing of hidden folders in Finder
# Written by Matthew Leong
# For Mac OS X 10.9 - Mavericks

defaults write com.apple.finder AppleShowAllFiles FALSE
# to use for 10.6-10.8, change to com.apple.Finder
killall Finder